# Symfony
- %SF_SYMFONY_LIB_DIR%/view/sfViewCacheManager.class.php
- %SF_SYMFONY_LIB_DIR%/routing/sfRoute.class.php
- %SF_SYMFONY_LIB_DIR%/view/sfPartialView.class.php
- %SF_SYMFONY_LIB_DIR%/escaper/sfOutputEscaper.class.php
- %SF_SYMFONY_LIB_DIR%/escaper/sfOutputEscaperArrayDecorator.class.php
- %SF_SYMFONY_LIB_DIR%/escaper/sfOutputEscaperGetterDecorator.class.php
- %SF_SYMFONY_LIB_DIR%/escaper/sfOutputEscaperObjectDecorator.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfIMessageSource.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfMessageSource.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfMessageSource_File.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfMessageSource_XLIFF.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfMessageFormat.class.php
- %SF_SYMFONY_LIB_DIR%/vendor/swiftmailer/classes/Swift/Mailer.php
- %SF_SYMFONY_LIB_DIR%/mailer/sfMailer.class.php
- %SF_SYMFONY_LIB_DIR%/util/sfInflector.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfI18N.class.php
- %SF_SYMFONY_LIB_DIR%/database/sfDatabase.class.php
- %SF_SYMFONY_LIB_DIR%/action/sfComponents.class.php
- %SF_SYMFONY_LIB_DIR%/util/sfCallable.class.php
- %SF_SYMFONY_LIB_DIR%/user/sfSecurityUser.class.php
- %SF_SYMFONY_LIB_DIR%/user/sfBasicSecurityUser.class.php

# Doctrine
# - %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine.php # failed in require_once "Doctrine/Core"
# - %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Core.php # can't define it without Doctrine.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Access.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Builder.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Cache/Interface.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Cache/Driver.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Cache/Apc.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Collection.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Configurable.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Adapter/Statement/Interface.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection/Common.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection/Module.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection/Mysql.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection/Statement.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/DataDict.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/DataDict/Mysql.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Event.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/EventListener/Interface.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/EventListener.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/EventListener/Chain.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Expression.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Expression/Driver.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Expression/Mysql.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Formatter.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Hydrator.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Hydrator/Abstract.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Hydrator/Graph.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Hydrator/RecordDriver.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Abstract.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Filter.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Filter/Standard.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Generator.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Iterator.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Listener/Interface.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Listener.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Listener/Chain.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/I18n.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Import/Builder.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Inflector.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Lib.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Locator/Injectable.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Manager.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Null.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Abstract.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Condition.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/From.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/JoinCondition.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Limit.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Orderby.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Part.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Registry.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Tokenizer.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Where.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Relation.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Relation/ForeignKey.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Relation/Parser.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Table.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Table/Repository.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Template.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Template/I18n.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Template/Listener/Timestampable.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Template/Timestampable.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Transaction.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Transaction/Mysql.php

# sfDoctrinePlugin
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php

# OpenPNE
- %SF_LIB_DIR%/vendor/doctrine_extensions/ExtraFunctions/lib/Doctrine/Connection/Mysql/ExtraFunctions.php
- %SF_LIB_DIR%/util/opAccessControlDoctrineTable.class.php
- %SF_LIB_DIR%/util/opDoctrineConnectionMysql.class.php
- %SF_LIB_DIR%/util/opDoctrineEventNotifier.class.php
- %SF_LIB_DIR%/util/opDoctrineMapperHydrator.class.php
- %SF_LIB_DIR%/util/opDoctrineModule_Formatter.class.php
- %SF_LIB_DIR%/util/opDoctrineQuery.class.php
- %SF_LIB_DIR%/util/opAccessControlRecordInterface.class.php
- %SF_LIB_DIR%/util/opDoctrineRecord.class.php
- %SF_LIB_DIR%/response/opWebResponse.class.php
- %SF_LIB_DIR%/view/opView.class.php
- %SF_LIB_DIR%/request/opWebRequest.class.php
- %SF_LIB_DIR%/i18n/opI18N.class.php
- %SF_LIB_DIR%/i18n/sfMessageSource_OpenPNECached.class.php
- %SF_LIB_DIR%/i18n/sfMessageSource_OpenPNE.class.php
- %SF_LIB_DIR%/user/opBaseSecurityUser.class.php
- %SF_LIB_DIR%/user/opAdaptableUser.class.php
- %SF_LIB_DIR%/user/opSecurityUser.class.php
- %SF_LIB_DIR%/user/opAuthAdapter.class.php
- %SF_LIB_DIR%/routing/opPatternRouting.class.php
- %SF_LIB_DIR%/routing/opLazyUnserializeRoutes.class.php
- %SF_LIB_DIR%/routing/opLazyUnserializeRoute.class.php
- %SF_LIB_DIR%/controller/opFrontWebController.class.php
- %SF_LIB_DIR%/filter/opExecutionFilter.class.php
- %SF_LIB_DIR%/filter/opEmojiFilter.class.php
- %SF_LIB_DIR%/filter/opCheckEnabledApplicationFilter.class.php
- %SF_LIB_DIR%/filter/opCacheControlFilter.class.php
- %SF_LIB_DIR%/filter/opAppendXRDSHeaderFilter.class.php
- %SF_LIB_DIR%/config/opConfig.class.php
- %SF_LIB_DIR%/config/opColorConfig.class.php
- %SF_LIB_DIR%/behavior/opActivateListener.class.php
- %SF_LIB_DIR%/behavior/opActivateBehavior.class.php

# most loaded tables
- %SF_LIB_DIR%/model/doctrine/MemberTable.class.php
- %SF_LIB_DIR%/model/doctrine/MemberConfigTable.class.php
- %SF_LIB_DIR%/model/doctrine/GadgetTable.class.php
- %SF_LIB_DIR%/model/doctrine/BannerUseImageTable.class.php
- %SF_LIB_DIR%/model/doctrine/BannerTable.class.php
- %SF_LIB_DIR%/model/doctrine/SnsTermTable.class.php
- %SF_LIB_DIR%/model/doctrine/SnsConfigTable.class.php

# most loaded models
- %SF_LIB_DIR%/model/doctrine/base/BaseMemberConfig.class.php
- %SF_LIB_DIR%/model/doctrine/MemberConfig.class.php
- %SF_LIB_DIR%/model/doctrine/base/BaseMember.class.php
- %SF_LIB_DIR%/model/doctrine/Member.class.php
- %SF_LIB_DIR%/model/doctrine/base/BaseGadget.class.php
- %SF_LIB_DIR%/model/doctrine/Gadget.class.php
- %SF_LIB_DIR%/model/doctrine/base/BaseBannerUseImage.class.php
- %SF_LIB_DIR%/model/doctrine/BannerUseImage.class.php
- %SF_LIB_DIR%/model/doctrine/base/BaseBanner.class.php
- %SF_LIB_DIR%/model/doctrine/Banner.class.php
- %SF_LIB_DIR%/model/doctrine/base/BaseSnsTerm.class.php
- %SF_LIB_DIR%/model/doctrine/SnsTerm.class.php
- %SF_LIB_DIR%/model/doctrine/base/BaseSnsConfig.class.php
- %SF_LIB_DIR%/model/doctrine/SnsConfig.class.php

# pc_frontend
- %SF_LIB_DIR%/controller/opPcFrontWebController.class.php
